
name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Black
      run: |
        python3 -m black --diff --check .

    - name: Isort
      run: |
        isort --check-only --diff .

    - name: Pytest
      run: |
        pytest
